### ISSUE TITLE
上传图片的同时处理图片的功能未能生效

### ISSUE THREAD

**Issue by tbto** [tencentyun/cos-snippets#3]
按照示例代码提交了，但是图片对象在服务端并未按照指定的rule做处理
![image](https://user-images.githubusercontent.com/3437980/94352906-87043f00-009d-11eb-923b-48511fe7cef5.png)

![image](https://user-images.githubusercontent.com/3437980/94352939-2295af80-009e-11eb-8a13-a2d1aaa3f954.png)

**Comment by tbto** [comment]
环境:.netcore 3.1 Newtonsoft.Json 12.0.3
示例代码中关于图片处理的Pic-Operation的json字符串化的时候，存在产生的字符串中默认保留有控制符号。
![image](https://user-images.githubusercontent.com/3437980/94353004-c2ebd400-009e-11eb-9cad-7a4fcac98982.png)

**Comment by konakonall** [comment]
已修改，请参考最新的示例
