### ISSUE TITLE
示例代码中关于图片处理的Pic-Operation的json字符串化的时候，产生的字符串中保留有控制符号

### ISSUE THREAD

**Issue by tbto** [tencentyun/cos-snippets#4]
环境:.netcore 3.1 Newtonsoft.Json 12.0.3
示例代码中关于图片处理的Pic-Operation的json字符串化的时候，存在产生的字符串中默认保留有控制符号。
![image](https://user-images.githubusercontent.com/3437980/94353004-c2ebd400-009e-11eb-9cad-7a4fcac98982.png)

**Comment by zhen-one** [comment]
我也是遇到这个问题了  无效的控制字符

**Comment by konakonall** [comment]
@tbto @q350241636 这里改成 `request.SetRequestHeader("Pic-Operation", o.ToString(Formatting.None));`，后续会更新仓库代码。

**Comment by konakonall** [comment]
示例已更新，请参考最新的示例 https://github.com/tencentyun/cos-snippets/blob/master/dotnet/dist/PictureOperation.cs
